### ISSUE TITLE
ruby cannot find perlin package

### ISSUE THREAD

**Issue by ksnortum** [blinry/sillypond#1]
(I don't know if you're still maintaining this, but here goes...)

When I run `make` it cannot find the perlin package:

        $ make
        #ruby sillypond.rb
        ruby sillypond.rb > music.ly
        <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:160:in `require': cannot load such file -- perlin (LoadError)
	        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:149:in `require'
	        from sillypond.rb:2:in `<main>'
        <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- perlin (LoadError)
	        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	        from sillypond.rb:2:in `<main>'
        make: *** [Makefile:3: default] Error 1

However, `gem` says the package is installed:

        $ gem list perlin
        
        *** LOCAL GEMS ***
        
        perlin (0.2.2)

**Comment by jeanas** [comment]
FWIW, for me it works. Must be something in your environment.

**Comment by ksnortum** [comment]
It looks like it was a permissions problem.  I had to change a few Ruby files to 644.  Now it is producing LilyPond silliness to its heart's content.

**Comment by ksnortum** [comment]
Local permissions problem, not a bug.
